ignoreWorkspaceRootCheck: true

minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@types/node@26.5.1'

trustPolicy: no-downgrade

update:
  ignoreDeps:
    - typescript@7

shellEmulator: true

packages:
  - playground
  - docs
  - packages/*
  - examples/*

allowBuilds:
  esbuild: true
  simple-git-hooks: true
